// <auto-generated />
using System;
using GpsApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GpsApp.Migrations
{
    [DbContext(typeof(GpsAppDbContext))]
    partial class GpsAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GpsApp.Domain.Aggregates.Package", b =>
                {
                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PackageId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SensorAttachedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SensorId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SensorId");

                    b.HasKey("PackageId");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("GpsApp.Domain.Aggregates.Shipment", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShipmentId");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ShipmentId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("ShipmentPackages", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShipmentId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("ShipmentPackages");
                });

            modelBuilder.Entity("GpsApp.Domain.Aggregates.Package", b =>
                {
                    b.OwnsOne("GpsApp.Domain.ValueObjects.Address", "Recipient", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("PackageId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.OwnsOne("GpsApp.Domain.ValueObjects.Address", "Sender", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("PackageId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.OwnsOne("GpsApp.Domain.ValueObjects.ExpectedRange<GpsApp.Domain.ValueObjects.Humidity>", "ExpectedHumidityRange", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("Maximum")
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal?>("Minimum")
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("PackageId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.OwnsOne("GpsApp.Domain.ValueObjects.ExpectedRange<GpsApp.Domain.ValueObjects.Temperature>", "ExpectedTemperatureRange", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("Maximum")
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal?>("Minimum")
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("PackageId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.Navigation("ExpectedHumidityRange");

                    b.Navigation("ExpectedTemperatureRange");

                    b.Navigation("Recipient")
                        .IsRequired();

                    b.Navigation("Sender")
                        .IsRequired();
                });

            modelBuilder.Entity("GpsApp.Domain.Aggregates.Shipment", b =>
                {
                    b.OwnsMany("GpsApp.Domain.ValueObjects.DeliveryLeg", "DeliveryLegs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid?>("GatewayId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("GatewayId");

                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("ShipmentId");

                            b1.ToTable("DeliveryLeg");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");

                            b1.OwnsOne("GpsApp.Domain.ValueObjects.Address", "EndAddress", b2 =>
                                {
                                    b2.Property<int>("DeliveryLegId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.HasKey("DeliveryLegId");

                                    b2.ToTable("DeliveryLeg");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryLegId");
                                });

                            b1.OwnsOne("GpsApp.Domain.ValueObjects.Address", "StartAddress", b2 =>
                                {
                                    b2.Property<int>("DeliveryLegId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.HasKey("DeliveryLegId");

                                    b2.ToTable("DeliveryLeg");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryLegId");
                                });

                            b1.Navigation("EndAddress")
                                .IsRequired();

                            b1.Navigation("StartAddress")
                                .IsRequired();
                        });

                    b.Navigation("DeliveryLegs");
                });

            modelBuilder.Entity("ShipmentPackages", b =>
                {
                    b.HasOne("GpsApp.Domain.Aggregates.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GpsApp.Domain.Aggregates.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
