version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

  app:
    build:
      context: ./GpsApp
    ports:
      - "5000:8080" # Adjust as needed
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MyDb;User Id=SA;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: http://*:8080
    depends_on:
      - sqlserver
    develop: # checks whether any updates have occured to GpsApp and then updates the docker automatically
      watch: 
        - action: sync
          path: ./GpsApp
          target: /app  
    volumes:
      - ./GpsApp:/app
    working_dir: /app
    command: ["dotnet", "watch", "run"]

volumes:
  sql_data:
