name: buildDbDocs

on:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
        ports:
          - 1433:1433

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download and extract SQL Server JDBC driver
        run: |
            curl -L -o sqljdbc.zip "https://download.microsoft.com/download/e/4/d/e4dffe06-df55-4cf2-9910-265f88c0a2e4/sqljdbc_12.4.2.0_enu.zip"
            unzip sqljdbc.zip -d sqljdbc
            mkdir -p drivers
            cp sqljdbc/sqljdbc_12.4/enu/mssql-jdbc-12.4.2.jre11.jar drivers/



      - name: Wait for SQL Server to be ready
        run: |
          sleep 32  # You can replace this with a real check if needed

      - name: Run migrations or schema setup
        run: |
          # TODO: Add command to run your setup SQL files against the db

      - name: Run SchemaSpy
        run: |
            docker run --rm \
            -v ${{ github.workspace }}/dbdocs:/output \
            -v ${{ github.workspace }}/drivers/mssql-jdbc-12.4.2.jre11.jar:/drivers/mssql-jdbc.jar \
            schemaspy/schemaspy:latest \
            -t mssql \
            -dp /drivers/mssql-jdbc.jar \
            -host sqlserver \
            -port 1433 \
            -db LocalDatabase \
            -u sa \
            -p ${{ secrets.SA_PASSWORD }} \
            -o /output


      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: schema-docs
          path: dbdocs
