# Linter for SQL Code using the tsqllint
# Link : https://github.com/tsqllint/tsqllint

name: Format SQL files

on: 
  push: 
    # Will run on push to all branches
    branches:
      - '**'
    paths:
      # Will only run on files under sql folder
      - 'sql/**'
  pull_request:
    # Will only run on pull_requests
    branches: [main, development]
    paths:
      - 'sql/**'
    workflow_dispatch:

jobs: 

  sql-lint: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install sqlfluff
      
      - name: Lint SQL files
        run: sqlfluff lint sql/ --config .github/workflows/.sqlfluff

      - name: Auto fix SQL files
        run: sqlfluff fix sql/ --config .github/workflows/.sqlfluff

